#ifndef SIXTRACKLIB_TESTLIB_COMMON_BEAM_ELEMENTS_BEAM_ELEMENTS_TRAITS_CXX_HPP__
#define SIXTRACKLIB_TESTLIB_COMMON_BEAM_ELEMENTS_BEAM_ELEMENTS_TRAITS_CXX_HPP__

#if defined( __cplusplus ) && !defined( _GPUCODE )
namespace SIXTRL_CXX_NAMESPACE
{
namespace tests
{

} /* namespace: tests */
} /* namespace: SIXTRL_CXX_NAMESPACE */


#endif /* C++, Host */

#endif /* SIXTRACKLIB_TESTLIB_COMMON_BEAM_ELEMENTS_BEAM_ELEMENTS_TRAITS_CXX_HPP__ */
