#ifndef SIXTRACKLIB_TESTLIB_COMMON_COBJECTS_COBJECTS_UNDEF_H__
#define SIXTRACKLIB_TESTLIB_COMMON_COBJECTS_COBJECTS_UNDEF_H__

#if defined( SIXTRL_TESTLIB_ARGPTR_DEC_UNDEF ) && \
    defined( SIXTRL_TESTLIB_ARGPTR_DEC )
    #undef SIXTRL_TESTLIB_ARGPTR_DEC_UNDEF
    #undef SIXTRL_TESTLIB_ARGPTR_DEC
#endif /* defined( SIXTRL_TESTLIB_ARGPTR_DEC_UNDEF ) &&
          defined( SIXTRL_TESTLIB_ARGPTR_DEC ) */

#if defined( SIXTRL_TESTLIB_DATAPTR_DEC_UNDEF ) && \
    defined( SIXTRL_TESTLIB_DATAPTR_DEC )
    #undef SIXTRL_TESTLIB_DATAPTR_DEC_UNDEF
    #undef SIXTRL_TESTLIB_DATAPTR_DEC
#endif /* defined( SIXTRL_TESTLIB_DATAPTR_DEC_UNDEF ) &&
          defined( SIXTRL_TESTLIB_DATAPTR_DEC ) */

#endif /* SIXTRACKLIB_TESTLIB_COMMON_COBJECTS_COBJECTS_UNDEF_H__ */
