#ifndef SIXTRACKLIB_BASE_COBJECTS_DEFINITIONS_UNDEF_H__
#define SIXTRACKLIB_BASE_COBJECTS_DEFINITIONS_UNDEF_H__

#if defined( SIXTRL_ARGPTR_DEC_UNDEF )
    #undef   SIXTRL_ARGPTR_DEC_UNDEF
    #undef   SIXTRL_ARGPTR_DEC
#endif /* !defined( SIXTRL_ARGPTR_DEC_UNDEF ) */

#if defined( SIXTRL_DATAPTR_DEC_UNDEF )
    #undef   SIXTRL_DATAPTR_DEC_UNDEF
    #undef   SIXTRL_DATAPTR_DEC
#endif /* !defined( SIXTRL_ARGPTR_DEC_UNDEF ) */

#if defined( SIXTRL_BUFFER_ARGPTR_DEC_UNDEF )
    #undef   SIXTRL_BUFFER_ARGPTR_DEC_UNDEF
    #undef   SIXTRL_BUFFER_ARGPTR_DEC
#endif /* !defined( SIXTRL_BUFFER_ARGPTR_DEC_UNDEF ) */

#if defined( SIXTRL_BUFFER_DATAPTR_DEC_UNDEF )
    #undef   SIXTRL_BUFFER_DATAPTR_DEC_UNDEF
    #undef   SIXTRL_BUFFER_DATAPTR_DEC
#endif /* !defined( SIXTRL_BUFFER_DATAPTR_DEC_UNDEF ) */

#if defined( SIXTRL_BUFFER_OBJ_ARGPTR_DEC_UNDEF )
    #undef SIXTRL_BUFFER_OBJ_ARGPTR_DEC_UNDEF
    #undef SIXTRL_BUFFER_OBJ_ARGPTR_DEC
#endif /* defined( SIXTRL_BUFFER_OBJ_ARGPTR_DEC_UNDEF ) */

#if defined( SIXTRL_BUFFER_OBJ_DATAPTR_DEC_UNDEF )
    #undef SIXTRL_BUFFER_OBJ_DATAPTR_DEC_UNDEF
    #undef SIXTRL_BUFFER_OBJ_DATAPTR_DEC
#endif /* defined( SIXTRL_BUFFER_OBJ_DATAPTR_DEC_UNDEF ) */

#if defined( SIXTRL_BUFFER_GARBAGE_ARGPTR_DEC_UNDEF )
    #undef SIXTRL_BUFFER_GARBAGE_ARGPTR_DEC_UNDEF
    #undef SIXTRL_BUFFER_GARBAGE_ARGPTR_DEC
#endif /* defined( SIXTRL_BUFFER_GARBAGE_ARGPTR_DEC_UNDEF ) */

#if defined( SIXTRL_BUFFER_GARBAGE_DATAPTR_DEC_UNDEF )
    #undef SIXTRL_BUFFER_GARBAGE_DATAPTR_DEC_UNDEF
    #undef SIXTRL_BUFFER_GARBAGE_DATAPTR_DEC
#endif /* defined( SIXTRL_BUFFER_GARBAGE_DATAPTR_DEC_UNDEF ) */

#endif /* SIXTRACKLIB_BASE_COBJECTS_DEFINITIONS_UNDEF_H__ */
