#ifndef SIXTRACKLIB_TESTLIB_COMMON_CONFIG_H__
#define SIXTRACKLIB_TESTLIB_COMMON_CONFIG_H__

#if !defined( SIXTRACKLIB_TESTLIB_GOOGLETEST_ENABLED )
    #define SIXTRACKLIB_TESTLIB_GOOGLETEST_ENABLED 1
#endif /* !defined( SIXTRACKLIB_TESTLIB_GOOGLETEST_ENABLED ) */

#endif /* SIXTRACKLIB_TESTLIB_COMMON_CONFIG_H__ */
