#ifndef SIXTRACKLIB_COMMON_INTERNAL_TYPE_ANNOTATIONS_H__
#define SIXTRACKLIB_COMMON_INTERNAL_TYPE_ANNOTATIONS_H__

#if !defined( _GPUCODE ) && defined( __clang__ )

/*  Helper macros, may not all be necessary */

#ifndef SIXTRL_ATTR_ANNOTATE_VALUE_STRINGIFY_2
    #define SIXTRL_ATTR_ANNOTATE_VALUE_STRINGIFY_2( value ) #value
#endif /* SIXTRL_ATTR_ANNOTATE_VALUE_STRINGIFY_2 */

#ifndef SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY_2
    #define SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY_2( key ) #key
#endif /* SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY_2 */

#ifndef SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY
    #define SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY( key ) SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY_2( key )
#endif /* SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY */

#ifndef SIXTRL_ATTR_ANNOTATE_VALUE_STRINGIFY
    #define SIXTRL_ATTR_ANNOTATE_VALUE_STRINGIFY( value ) SIXTRL_ATTR_ANNOTATE_VALUE_STRINGIFY_2( value )
#endif /* SIXTRL_ATTR_ANNOTATE_VALUE_STRINGIFY */

#ifndef SIXTRL_ATTR_ANNOTATE_KV_STRINGIFY
    #define SIXTRL_ATTR_ANNOTATE_KV_STRINGIFY( key, value ) #key ":=" #value
#endif /* SIXTRL_ATTR_ANNOTATE_KV_STRINGIFY */

#ifndef SIXTRL_ATTR_ANNOTATE_KEY_STRVALUE_STRINGIFY
    #define SIXTRL_ATTR_ANNOTATE_KEY_STRVALUE_STRINGIFY( key, value ) #key ":=" value
#endif /* SIXTRL_ATTR_ANNOTATE_KEY_STRVALUE_STRINGIFY */

/* Annotation macros: */

#ifndef SIXTRL_ANNOTATE_COBJECT
    #define SIXTRL_ANNOTATE_COBJECT \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY(cobject))))
#endif /* SIXTRL_ANNOTATE_COBJECT */

#ifndef SIXTRL_ANNOTATE_ELEM_OBJ
    #define SIXTRL_ANNOTATE_ELEM_OBJ \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY(sixtrl_elem_obj))))
#endif /* SIXTRL_ANNOTATE_ELEM_OBJ */

#ifndef SIXTRL_ANNOTATE_ELEM_OBJ_API_NAME
    #define SIXTRL_ANNOTATE_ELEM_OBJ_API_NAME( value ) \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KV_STRINGIFY(sixtrl_elem_obj_api_name,value))))
#endif /* SIXTRL_ANNOTATE_ELEM_OBJ_API_NAME */

#ifndef SIXTRL_ANNOTATE_ELEM_OBJ_DEC
    #define SIXTRL_ANNOTATE_ELEM_OBJ_DEC( value ) \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRVALUE_STRINGIFY(sixtrl_elem_obj_dec,value))))
#endif /* SIXTRL_ANNOTATE_ELEM_OBJ_DEC */


#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_DISABLED
    #define SIXTRL_ANNOTATE_ELEM_FIELD_DISABLED \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY(sixtrl_elem_field_disabled))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_DISABLED */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_NOT_BY_VALUE
    #define SIXTRL_ANNOTATE_ELEM_FIELD_NOT_BY_VALUE \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY(sixtrl_elem_field_not_by_val))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_NOT_BY_VALUE */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_CONST
    #define SIXTRL_ANNOTATE_ELEM_FIELD_CONST \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY(sixtrl_elem_field_const))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_CONST */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_REQU_INIT
    #define SIXTRL_ANNOTATE_ELEM_FIELD_REQU_INIT \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY(sixtrl_elem_field_requ_init))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_REQU_INIT */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_API_NAME
    #define SIXTRL_ANNOTATE_ELEM_FIELD_API_NAME(value) \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KV_STRINGIFY(sixtrl_elem_field_api_name,value))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_API_NAME */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_DEFAULT_VALUE
    #define SIXTRL_ANNOTATE_ELEM_FIELD_DEFAULT_VALUE(value) \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KV_STRINGIFY(sixtrl_elem_field_default_value, value))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_DEFAULT_VALUE */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_DEC
    #define SIXTRL_ANNOTATE_ELEM_FIELD_DEC(value) \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KV_STRINGIFY(sixtrl_elem_field_dec, value))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_DEC */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY(sixtrl_elem_field_pointer))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_EXT_POINTER
    #define SIXTRL_ANNOTATE_ELEM_FIELD_EXT_POINTER \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY(sixtrl_elem_field_ext_pointer))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_EXT_POINTER */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_TYPE
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_TYPE( value ) \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KV_STRINGIFY(sixtrl_elem_field_ptr_type,value))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_TYPE */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_API_NAME
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_API_NAME( value ) \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KV_STRINGIFY(sixtrl_elem_field_ptr_api_name,value))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_API_NAME */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_DEC
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_DEC( value ) \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRVALUE_STRINGIFY(sixtrl_elem_field_ptr_dec,value))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_DEC */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_LENGTH
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_LENGTH( value ) \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KV_STRINGIFY(sixtrl_elem_field_ptr_length,value))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_LENGTH */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_IS_ARRAY
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_IS_ARRAY \
        __attribute__((annotate(SIXTRL_ATTR_ANNOTATE_KEY_STRINGIFY(sixtrl_elem_field_ptr_is_array))))
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_IS_ARRAY */

#else

#ifndef SIXTRL_ANNOTATE_COBJECT
    #define SIXTRL_ANNOTATE_COBJECT
#endif /* SIXTRL_ANNOTATE_COBJECT */

#ifndef SIXTRL_ANNOTATE_ELEM_OBJ
    #define SIXTRL_ANNOTATE_ELEM_OBJ
#endif /* SIXTRL_ANNOTATE_ELEM_OBJ */

#ifndef SIXTRL_ANNOTATE_ELEM_OBJ_API_NAME
    #define SIXTRL_ANNOTATE_ELEM_OBJ_API_NAME( value )
#endif /* SIXTRL_ANNOTATE_ELEM_OBJ_API_NAME */

#ifndef SIXTRL_ANNOTATE_ELEM_OBJ_DEC
    #define SIXTRL_ANNOTATE_ELEM_OBJ_DEC( value )
#endif /* SIXTRL_ANNOTATE_ELEM_OBJ_DEC */



#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_DISABLED
    #define SIXTRL_ANNOTATE_ELEM_FIELD_DISABLED
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_DISABLED */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_NOT_BY_VALUE
    #define SIXTRL_ANNOTATE_ELEM_FIELD_NOT_BY_VALUE
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_NOT_BY_VALUE */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_CONST
    #define SIXTRL_ANNOTATE_ELEM_FIELD_CONST
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_CONST */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_REQU_INIT
    #define SIXTRL_ANNOTATE_ELEM_FIELD_REQU_INIT
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_REQU_INIT */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_API_NAME
    #define SIXTRL_ANNOTATE_ELEM_FIELD_API_NAME(value)
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_API_NAME */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_DEFAULT_VALUE
    #define SIXTRL_ANNOTATE_ELEM_FIELD_DEFAULT_VALUE(value)
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_DEFAULT_VALUE */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_DEC
    #define SIXTRL_ANNOTATE_ELEM_FIELD_DEC(value)
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_DEC */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_EXT_POINTER
    #define SIXTRL_ANNOTATE_ELEM_FIELD_EXT_POINTER
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_EXT_POINTER */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_TYPE
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_TYPE( value )
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_TYPE */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_API_NAME
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_API_NAME( value )
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_API_NAME */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_DEC
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_DEC( value )
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_DEC */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_LENGTH
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_LENGTH( value )
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_LENGTH */

#ifndef SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_IS_ARRAY
    #define SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_IS_ARRAY
#endif /* SIXTRL_ANNOTATE_ELEM_FIELD_POINTER_IS_ARRAY */

#endif /* Host && ( gcc / g++ || llvm/clang ) */
#endif /* SIXTRACKLIB_COMMON_INTERNAL_TYPE_ANNOTATIONS_H__ */
