#ifndef SIXTRACKLIB_COMMON_PARTICLES_COBJ_TYPE_IDS_UNDEF_H__
#define SIXTRACKLIB_COMMON_PARTICLES_COBJ_TYPE_IDS_UNDEF_H__

#if defined( SIXTRL_COBJECTS_TYPE_ID_SINGLE_PARTICLE )
    #undef SIXTRL_COBJECTS_TYPE_ID_SINGLE_PARTICLE
#endif /* defined( SIXTRL_COBJECTS_TYPE_ID_SINGLE_PARTICLE ) */

#if defined( SIXTRL_COBJECTS_TYPE_ID_PARTICLES_COLLECTION )
    #undef SIXTRL_COBJECTS_TYPE_ID_PARTICLES_COLLECTION
#endif /* defined( SIXTRL_COBJECTS_TYPE_ID_PARTICLES_COLLECTION ) */

#if defined( SIXTRL_COBJECTS_TYPE_ID_PARTICLES_ADDR )
    #undef SIXTRL_COBJECTS_TYPE_ID_PARTICLES_ADDR
#endif /* defined( SIXTRL_COBJECTS_TYPE_ID_PARTICLES_ADDR ) */

#endif /* SIXTRACKLIB_COMMON_PARTICLES_COBJ_TYPE_IDS_UNDEF_H__ */
