#ifndef SIXTRACKLIB_COMMON_TACK_COBJ_TYPE_IDS_UNDEF_H__
#define SIXTRACKLIB_COMMON_TACK_COBJ_TYPE_IDS_UNDEF_H__

#if defined( SIXTRL_COBJECTS_TYPE_ID_TRACK_CONFIG )
    #undef SIXTRL_COBJECTS_TYPE_ID_TRACK_CONFIG
#endif /* defined( SIXTRL_COBJECTS_TYPE_ID_TRACK_CONFIG ) */

#if defined( SIXTRL_COBJECTS_TYPE_ID_ELEM_BY_ELEM_CONFIG )
    #undef SIXTRL_COBJECTS_TYPE_ID_ELEM_BY_ELEM_CONFIG
#endif /* defined( SIXTRL_COBJECTS_TYPE_ID_ELEM_BY_ELEM_CONFIG ) */

#endif /* SIXTRACKLIB_COMMON_TACK_COBJ_TYPE_IDS_UNDEF_H__ */
