#ifndef SIXTRACKLIB_COMMON_BEAM_ELEMENTS_UNDEF_H__
#define SIXTRACKLIB_COMMON_BEAM_ELEMENTS_UNDEF_H__

#if defined( SIXTRL_TRACK_ARGPTR_DEC_UNDEF ) && defined( SIXTRL_TRACK_ARGPTR_DEC )
    #undef SIXTRL_TRACK_ARGPTR_DEC_UNDEF
    #undef SIXTRL_TRACK_ARGPTR_DEC
#endif /* defined( SIXTRL_TRACK_ARGPTR_DEC_UNDEF ) &&
          defined( SIXTRL_TRACK_ARGPTR_DEC ) */

#if defined( SIXTRL_TRACK_DATAPTR_DEC_UNDEF ) && defined( SIXTRL_TRACK_DATAPTR_DEC )
    #undef SIXTRL_TRACK_DATAPTR_DEC_UNDEF
    #undef SIXTRL_TRACK_DATAPTR_DEC
#endif /* defined( SIXTRL_TRACK_DATAPTR_DEC_UNDEF ) &&
          defined( SIXTRL_TRACK_DATAPTR_DEC ) */

#endif /* SIXTRACKLIB_COMMON_BEAM_ELEMENTS_UNDEF_H__ */
