#ifndef SIXTRACKLIB_TESTS_TESTLIB_IMPL_GENERIC_OBJECT_TYPE_UNDEF_H__
#define SIXTRACKLIB_TESTS_TESTLIB_IMPL_GENERIC_OBJECT_TYPE_UNDEF_H__

#if defined( SIXTRL_GENOBJ_ARGPTR_DEC_UNDEF ) && \
    defined( SIXTRL_GENOBJ_ARGPTR_DEC )
        #undef SIXTRL_GENOBJ_ARGPTR_DEC
        #undef SIXTRL_GENOBJ_ARGPTR_DEC_UNDEF
#endif /* defined( SIXTRL_GENOBJ_ARGPTR_DEC_UNDEF ) */

#if defined( SIXTRL_GENOBJ_DATAPTR_DEC_UNDEF ) && \
    defined( SIXTRL_GENOBJ_DATAPTR_DEC )
        #undef SIXTRL_GENOBJ_DATAPTR_DEC
        #undef SIXTRL_GENOBJ_DATAPTR_DEC_UNDEF
#endif /* defined( SIXTRL_GENOBJ_DATAPTR_DEC_UNDEF ) */

#endif /* SIXTRACKLIB_TESTS_TESTLIB_IMPL_GENERIC_OBJECT_TYPE_UNDEF_H__ */

/* end: tests/sixtracklib/testlib/impl/generic_obj_undef.h */
