#ifndef SIXTRACKLIB_COMMON_COBJECTS_UNDEF_H__
#define SIXTRACKLIB_COMMON_COBJECTS_UNDEF_H__

#if defined( SIXTRL_CBUFFER_ARGPTR_DEC_UNDEF ) && \
    defined( SIXTRL_CBUFFER_ARGPTR_DEC )
    #undef SIXTRL_CBUFFER_ARGPTR_DEC_UNDEF
    #undef SIXTRL_CBUFFER_ARGPTR_DEC
#endif /* !defined( SIXTRL_CBUFFER_ARGPTR_DEC ) */

#if defined( SIXTRL_CBUFFER_DATAPTR_DEC_UNDEF ) && \
    defined( SIXTRL_CBUFFER_DATAPTR_DEC )
    #undef SIXTRL_CBUFFER_DATAPTR_DEC_UNDEF
    #undef SIXTRL_CBUFFER_DATAPTR_DEC
#endif /* !defined( SIXTRL_CBUFFER_DATAPTR_DEC ) */

#if defined( SIXTRL_CBUFFER_OBJ_ARGPTR_DEC_UNDEF ) && \
    defined( SIXTRL_CBUFFER_OBJ_ARGPTR_DEC )
    #undef SIXTRL_CBUFFER_OBJ_ARGPTR_DEC_UNDEF
    #undef SIXTRL_CBUFFER_OBJ_ARGPTR_DEC
#endif /* !defined( SIXTRL_CBUFFER_OBJ_ARGPTR_DEC ) */

#if defined( SIXTRL_CBUFFER_OBJ_DATAPTR_DEC_UNDEF ) && \
    defined( SIXTRL_CBUFFER_OBJ_DATAPTR_DEC )
    #undef SIXTRL_CBUFFER_OBJ_DATAPTR_DEC_UNDEF
    #undef SIXTRL_CBUFFER_OBJ_DATAPTR_DEC
#endif /* !defined( SIXTRL_CBUFFER_OBJ_DATAPTR_DEC ) */

#if defined( SIXTRL_CBUFFER_GARBAGE_ARGPTR_DEC_UNDEF ) && \
    defined( SIXTRL_CBUFFER_GARBAGE_ARGPTR_DEC )
    #undef SIXTRL_CBUFFER_GARBAGE_ARGPTR_DEC_UNDEF
    #undef SIXTRL_CBUFFER_GARBAGE_ARGPTR_DEC
#endif /* !defined( SIXTRL_CBUFFER_GARBAGE_ARGPTR_DEC ) */

#if defined( SIXTRL_CBUFFER_GARBAGE_DATAPTR_DEC_UNDEF ) && \
    defined( SIXTRL_CBUFFER_GARBAGE_DATAPTR_DEC )
    #undef SIXTRL_CBUFFER_GARBAGE_DATAPTR_DEC_UNDEF
    #undef SIXTRL_CBUFFER_GARBAGE_DATAPTR_DEC
#endif /* !defined( SIXTRL_CBUFFER_GARBAGE_DATAPTR_DEC ) */

#endif /* SIXTRACKLIB_COMMON_COBJECTS_UNDEF_H__ */
