[opencl]
    scenario = "demo01_sc1"
    compile_flags = [ "-DSIXTRL_USE_SINGLE_PARTICLE_ADAPTER=1",
                      "-DSIXTRL_TRACK_BEAMBEAM4D=0",
                      "-DSIXTRL_TRACK_BEAMBEAM6D=0",
                      "-DSIXTRL_TRACK_SPACECHARGE=1",
                      "-DSIXTRL_TRACK_TRICUB=0", ]

